### ISSUE TITLE
Is there any plan regarding gathering a set of rules like `\begin{mathpar}`?

### ISSUE THREAD

**Issue by ice1000** [pauladam94/curryst#14]
Right now I'm doing this and I think this is cringe:

![image](https://github.com/pauladam94/curryst/assets/16398479/4dc2e7db-4c5f-4bed-87ac-0ed50b327bb4)

**Comment by pauladam94** [comment]
Thank you for your feedback.
Can you be more precise about you're demand ? 
Is it about the ways to typesetting a lot of inference rules in a column ?
What does mathpar does that this package does not ? 
Indeed a lot of the work of this package is to reimplement behaviour of LaTeX package.

**Comment by ice1000** [comment]
> Is it about the ways to typesetting a lot of inference rules in a column ?

Like it separates the rules with some spaces and if there's two many rules in a line, it breaks into multiple lines.

**Comment by pauladam94** [comment]
Yes Indeed it is a feature that is in our to-do list.
It is not very easy to do, but we are thinking about it. Our goal is to stay in a 1 file project, because we are trying to do a simple as possible package.

Why it is not yet implemented :
1. I don't know how to get the space that a rule "have". I want to have a width that tells me : "this is bigger than the width of the page".
    - context and style has changed in 0.11 of typst so I have not dig how to do that
2. We have focus on tree of rules to typeset right instead of perfectly typeset Big rules with a lot of premisses
3. I don't have yet a good idea of an algorithm to manage multiple lines. I have to dig a little bit in the output of mathpartir (the latex package)

If you have any suggestions or want to give some help do not hesitate.

**Comment by MDLC01** [comment]
Regarding your first point, [the `layout` function](https://typst.app/docs/reference/layout/layout/) is what you are looking for.

**Comment by MDLC01** [comment]
I started working on a PR for that. Is this the kind of this you would expect in case there is not enough horizontal space?

![The premises are laid out in a vertical stack.](https://github.com/pauladam94/curryst/assets/57839069/373b38b8-16d5-401b-a6e2-b619060abe85)

How should the premises be aligned horizontally?

**Comment by pauladam94** [comment]
However you want to have something like this ?
```txt
    Rule1     Rule2     Rule3
        Rule4        Rule5
---------------------------
             Conclusion
```
When there is not enough space ? (for example in double columns style of an article)

**Comment by pauladam94** [comment]
- The problem of typesetting the rules with multiple lines ressemble the problem of the [Knapsack Problem](https://en.wikipedia.org/wiki/Knapsack_problem) where we have to stack the premisses width without never exceed the width of the page.

# First Idea : 
- Having an algorithm that tries to type_set with n lines
- trying for n=1, n=2 ... until we have a sucessfull typset 
```C
If (not enough_space) and (single_rule_without_tree) {
    number_lines_premisses = 1
    while(not enough_space) {
        enough_space = typesetting_premisses_multiple_lines(number_lines_premisses) // This has to be 
        number_lines_premisses += 1
    }
} else {
   classic_type_setting_version_2.0
}
```

## Analyse the problem as a decomposition of integer problems (does'nt take into account the size of the rules)
First Idea to typeset multiples lines of premisses  :
type_set_multiple_lines(nb_prem, nb_lines) {
    decompose nb_prem as a sum of nb_lines integers that adds_up to nb_prem.
}

For example with 5 premisses and 2 lines : 5 = 2 + 3
So there will be :
- 2 premisses in the first line
- 3 premisses in the second line

If 6 premisses 4 lines : 6 = 1 + 1 + 2 + 2

---

- However it seems to long to compute (not very efficient)
- Can

# Greedy algorithm taking into account the size of the rules
- I think we should not change the order of the premisses given by the user. This is very important and will make the greedy algorithm fast.

function type_set(premisses) {
lines = [] 
// Lines is a 2D array that stores a list of line
// A Line is a list of premisse

```C
current_line = 0
FOR prem in premisses DO
    IF (line[current_line] + premisse >(exceed) width_page) and (lines[current_line].len > 1) {
        current_line += 1
    }
    lines[current_lines].append(prem)
DONE
```

**Comment by MDLC01** [comment]
Although I like the idea of finding a general solution that works for any tree, I think most of the time, this problem arises with trees that only consists of a single rule application. It may be a bit overkill to make a complex algorithm that will mostly be used in this basic case.

**Comment by ice1000** [comment]
> However you want to have something like this ?
> ```C
>   Rule1     Rule2     Rule3
>       Rule4      Rule5
> -----------------------------
>            Conclusion
> ```
> When there is not enough space ? (for example in double columns style of an article)

Exactly!!

**Comment by MDLC01** [comment]
I would say this is out of the scope of Curryst. You can probably reproduce that yourself with something like
```typ
#let mathpar(..rules) = block(
  breakable: true,
  rules.pos().join(h(0.5cm)),
)
```

**Comment by Lelio-Brun** [comment]
I see, you're right, actually `mathpar` is also intended as a general purpose math paragraph, not specifically targeting inference rules.
