### ISSUE TITLE
Math mode text problem

### ISSUE THREAD

**Issue by yiyuan-cao** [pauladam94/curryst#20]
`smallcaps` text isn't properly rendered in math mode. Example:
```typst
$ proof-tree(rule(name: smallcaps[EvenZero], $op("even") 0$, $$)) $
```

**Comment by MDLC01** [comment]
I don't think this is related to Curryst specifically. See typst/typst#3138.

**Comment by yiyuan-cao** [comment]
Thanks for the information!
