### ISSUE TITLE
Is it impossible to style labels and names?

### ISSUE THREAD

**Issue by Lelio-Brun** [pauladam94/curryst#22]
I've been trying to do things like: 
```
rule(name: smallcaps("Foo"), ...)
```
But it seems like formatting (I also tried bold, italics, and colors) is simply ignored.

**Comment by MDLC01** [comment]
This should work. Are you sure the font you are using supports small capitals?

**Comment by Lelio-Brun** [comment]
Yes, small capitals are supported.

**Comment by MDLC01** [comment]
The following works as intended for me (Typst 0.11.1, Curryst 0.3.0):
```typ
#import "@preview/curryst:0.3.0": rule, proof-tree
#proof-tree(rule(name: smallcaps[Test], label: smallcaps[Test], smallcaps[Test]))
```
![The label, name, and conclusion are all using small capitals.](https://github.com/user-attachments/assets/96740a4c-4193-4362-b13d-aafd7766393a)

Could you send a minimal reproduction of the issue?

**Comment by Lelio-Brun** [comment]
Ah! Yes, here is one: 
```typst
#import "@preview/curryst:0.3.0": rule, proof-tree
$#proof-tree(rule(name: smallcaps[Test], label: smallcaps[Test], smallcaps[Test]))$
```
It seems that it is because of the math mode. Is it expected?

**Comment by MDLC01** [comment]
Typst's default math font (New Computer Modern Math) does not support small capitals.

**Comment by Lelio-Brun** [comment]
I see, it makes sense; I would have thought that content displayed in math mode would use the document body font.
That being said, bold and italics do not work either, which is more surprising. 
All of the following expressions have no effect:
```typst
$#[_foo_]$
$#[*foo*]$
$#[#smallcaps[foo]]$
```

**Comment by MDLC01** [comment]
This is because the math typeface does not support italic and bold either. What happens when you use `math.bold` and `math.italic` is that different Unicode characters are used, but the font (as in, typeface + weight, style, etc.) stays the same.

**Comment by Lelio-Brun** [comment]
Ah I see, thanks for the explanation!
