### ISSUE TITLE
Multi-level sub-/superscripts result in visual overlap

### ISSUE THREAD

**Issue by JaSpa** [pauladam94/curryst#23]
Using multiple levels of subscripts in the premises, or superscripts in the conclusion can lead to a visual overlap with the separator line, or, in extreme cases, even between the premise and the conclusion themselves.

Demo: https://typst.app/project/rVOAELeGg2h50MB3Iqdhsl

As a reference point, the mathpartir package in LaTeX avoids any overlap: https://www.overleaf.com/read/htfdymdhqhnp#5da106

**Comment by MDLC01** [comment]
This is due to typst/typst#1028. Until this is fixed, I recommend you use block equations instead of inline equations:

```typ
#import "@preview/curryst:0.3.0": rule, proof-tree

#let infer(conclusion, ..premise) = proof-tree(rule(conclusion, ..premise))

#proof-tree(rule($ text("conclusion")^A^B^C $, $ text("premise")_A_B_C $))

#v(1cm)

#proof-tree(rule($ text("conclusion")^A^B^C $, $ text("premise")_A_B_C_D_E $))
```

![There is no overlap.](https://github.com/user-attachments/assets/d618683a-177e-4514-9f5a-b6cb61e429ec)
