### ISSUE TITLE
Centering an inference rule on the horizontal line.

### ISSUE THREAD

**Issue by alexarice** [pauladam94/curryst#26]
I have some inference rules which I want to look like the following:

```
 A      
---    ---
 B      B
```
following the advice in #14, I can create something similar but by default the rule with an empty premise will be aligned differently. I can hack around this by adding `hide($A$)` as a premise to this rule but was wondering if there's any way to set the horizontal line as the "anchor" (unsure if this is the correct terminology)

**Comment by MDLC01** [comment]
There is no way to set the baseline of a box in Typst at the moment, so this issue cannot be solved other than by using the above workaround for now.

**Comment by MDLC01** [comment]
For the reason stated above, I will close the issue for now. If at some point Typst adds the ability to specify a baseline to blocks, feel free to reopen this issue (or open a new one if you can't reopen this one).
