### ISSUE TITLE
Conclusion comes before the premisses?

### ISSUE THREAD

**Issue by hugomg** [pauladam94/curryst#28]
Sorry if this isn't a proper issue. I really like this library but I keep getting confused that we have to write rule(conclusion, premise) instead of rule(premise, conclusion).

If we write one per line, the first argument appears above the others, but it gets rendered the other way around.

    rule(
        conclusion,
        premise,
    )

In Latex's mathpartir package, the conclusion is second

    \inferrule{premise}{conclusion}

**Comment by MDLC01** [comment]
There are many subtly different ways the API could behave,none of which is obviously better. If you are not satisfied with the one used by Curryst, you can write a simple wrapper around it to have the API you want.

**Comment by MDLC01** [comment]
I will close this issue because there is simply no solution that would satisfy everyone, and at this point this would be a significant breaking change.

**Comment by pauladam94** [comment]
To respond to @hugomg.

We have always admit that they are only on conclusions. The two next argument explain what when admitting this we have choosen to put premisses after conclusion.

- First this choice has been taken to be able to utilize the typst syntax. Indeed the last argument can be of any number of element (and in the function we get back a list of argument).
This could be changed, but this is easy to implement in Typst in this way and have no named argument.

- Other argument, all functions in typst (native ones) that have a possibility to have multiple content parameter are always the last parameter (for exemple table and grid function). I think that this statement is correct and that justifies the possible multiple argument (for premisses) at the end.

I also agree with the comment of @MDLC01 that this is just a taste thing and we will probably never agree 👍
