### ISSUE TITLE
Inconsistent horizontal line spacing

### ISSUE THREAD

**Issue by MDLC01** [pauladam94/curryst#3]
The following rules are the same, except with different names. Notice how `name: none` is not rendered the same as `name: []`, and how using a zero width space as the name is necessary to get the same spacing as a rule with a normal name for a rule without a name.

![image](https://github.com/pauladam94/curryst/assets/57839069/ae0870ed-9ab2-4c96-a373-693862285988)

**Comment by pauladam94** [comment]
Yes indeed I measure the size of the title. Is it actually not wanted behaviour ?
The typeset of the rule should take into account the size of the title, no matter what is display. It is more of a Typst issue than one of the package in my opinion.

This behaviour could be changed using is statement, I don't know if it's the right way to think about it however.
You can of course propose a fix, if you have an idea.

**Comment by MDLC01** [comment]
I think the spacing here should be at least the one of the last two rules in the examples I gave (so a `max` of the current spacing and something like `1em`, although this would have to be determined). Therefore, you don't get misalignment when some rules in a tree have a name, and others don't, but rules with higher names still get spaced properly when you have such rules.

I will try to implement a fix before next week.
