### ISSUE TITLE
Feature request: allow trees with no rule

### ISSUE THREAD

**Issue by MDLC01** [pauladam94/curryst#8]
I would like to be able to write the following:
```typ
#proof-tree($x$)
```

I expect this to work because this is essentially the smallest form of a tree: a tree that uses no rule, just a leaf.

This would be useful because the user might have a function that generates trees, and where the base case is some content instead of a 0-ary rule.

Adding this feature would not break anything – in fact, it would even make the code cleaner in my opinion.

**Comment by pauladam94** [comment]
If it's more general and clean in the code, it will indeed be a good idea.
